version: '3'

services:
  mysql-master:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wms
      MYSQL_DATABASE: wms
      MYSQL_USER: wms
      MYSQL_PASSWORD: wms
    volumes:
      - mysql-master:/var/lib/mysql
    networks:
      - mysql-network
    ports:
      - 3306:3306

  mysql-slave:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wms
      MYSQL_DATABASE: wms
      MYSQL_USER: wms
      MYSQL_PASSWORD: wms
    volumes:
      - mysql-slave:/var/lib/mysql
    networks:
      - mysql-network
    depends_on:
      - mysql-master
    ports:
      - 3307:3306

volumes:
  mysql-master:
  mysql-slave:

networks:
  mysql-network: