spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  datasource:
    master:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      jdbc-url: jdbc:p6spy:mysql://localhost:3306/wms?useSSL=false&allowPublicKeyRetrieval=true
      pool-name: master
      connection-test-query: SELECT 1
      username: wms
      password: wms
    slave:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      jdbc-url: jdbc:p6spy:mysql://localhost:3307/wms?useSSL=false&allowPublicKeyRetrieval=true
      pool-name: slave
      connection-test-query: SELECT 1
      username: wms
      password: wms
